services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: survey_app_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "3011:3001"
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      RAILS_ENV: development
    volumes:
      - ./backend:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
    command: sh -c "rm -f tmp/pids/server.pid && rails db:create && rails db:migrate && rails server -b 0.0.0.0 -p 3001"

  frontend:
    build: ./frontend
    ports:
      - "3010:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:3011
    depends_on:
      - backend
    command: sh -c "npm start"

volumes:
  postgres_data:
  bundle_cache:
