services:
  - type: web
    name: survey-app-backend
    region: singapore
    runtime: ruby
    plan: free
    rootDir: backend
    buildCommand: |
      bundle install
    startCommand: |
      RAILS_ENV=production bundle exec rails db:migrate && \
      RAILS_ENV=production bundle exec rails server -b 0.0.0.0 -p $PORT
    healthCheckPath: /up
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: survey-app-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: true

  - type: web
    name: survey-app-frontend
    runtime: static
    rootDir: frontend
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: "https://survey-app-backend-bjw3.onrender.com"

databases:
  - name: survey-app-db
    region: singapore 
    databaseName: survey_app_production
    user: survey_app_user
    plan: free